#!/bin/sh
set -e
REPO=/home/pi/rpi-firmware
REPOURL=git://10.0.0.1/raspberrypi/firmware.git

if [ ! -d "$REPO/.git" ]; then
	git clone --depth=1 "$REPOURL" "$REPO"
fi

cd /home/pi/rpi-firmware

git fetch --depth 1
git reset --hard origin/HEAD

sudo rsync -rcP boot/ /boot/

sudo rsync -rcPpl --delete hardfp/opt/vc /opt

sudo rsync -rcPpl modules/ /lib/modules/
